version: '3.7'

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/vue
  nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/nginx
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/log
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django/static
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django/media

services:
  vue:
    build: 
      context: ./vue
    container_name: vue
    command: "npm run serve"
    volumes:
      - frontend:/usr/src/app
    user: "${USERID}:${GROUPID}"
    ports:
      - "8080:8080"