version: '3.7'

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/data/postgresdata
  postgres_backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/postgresdata_backup_server
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/vue
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/log
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/static
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/media


networks:
  default:
    external:
      name: nginx-proxy_default