version: '3.7'

services:  
  django:
    restart: always
    build: ./django
    container_name: django
    user: "${USER}:${GROUP}"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - VIRTUAL_PROTO=uwsgi
    user: "${USERID}:${GROUPID}"
    depends_on: 
      - postgres
    volumes:
      - django:/www/site
      - frontend:/www/site/frontend
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    container_name: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    restart: unless-stopped
    container_name: nginx
    build: 
      context: ./nginx
    environment:
      - VIRTUAL_HOST=lolo.localhost
    volumes:
      - nginx:/etc/nginx/conf.d
      - django:/www/site
      - static:/www/static
      - media:/www/media
      - log:/log
    expose: 
      - 80
    depends_on: 
      - django
      - postgres

networks:
  default:
    external:
      name: nginx-proxy_default