version: '3'

services:
  vue:
    build: ./vue
    container_name: vue
    volumes:
      - ./vue:/usr/src/app
    user: "${USERID}:${GROUPID}"
    ports:
      - "8080:8080"

  django:
    build: ./django
    container_name: django
    volumes:
      - ./django:/www/site
      - ./vue:/www/site/frontend
    environment:
      PYTHONUNBUFFERED: "TRUE"
    user: "${USERID}:${GROUPID}"
    ports:
      - "8000:8000"
    restart: always

