version: '3.7'

services:  
  django:
    restart: always
    build: ./django
    container_name: django
    user: "${USERID}:${GROUPID}"
    depends_on: 
      - postgres
    volumes:
      - django:/www/site
      - frontend:/www/site/frontend
      - media:/www/media
      - static:/www/static

  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    container_name: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - postgres_backup:/var/backup
