version: '3'

services:
  vue:
    build: ./vue
    container_name: vue
    volumes:
      - ${PWD}/vue:/usr/src/app
    command: "npm run serve"
    user: "${USERID}:${GROUPID}"
    ports:
      - "8080:8080"

  django:
    build: ./django
    container_name: django
    volumes:
      - ${PWD}/django:/www/site
      - ${PWD}/vue:/www/site/frontend
    environment:
      PYTHONUNBUFFERED: "TRUE"
    user: "${USERID}:${GROUPID}"
    ports:
      - "3000:3000"
    restart: always

  postgres:
    build: "./postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/pgdata
