version: '3.7'

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
  postgres_backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata_backup
  postgres_backup_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata_backup_server
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/vue
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/log
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/static
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/media

services:
  postgres:
    ports:
      - 5432:5432
    volumes:
      - postgres_backup:/var/backup
      - postgres_backup_server:/var/backup_server

  node:
    restart: unless-stopped
    build: 
      context: ./vue
    container_name: node
    command: "npm run serve"
    volumes:
      - frontend:/usr/src/app
    user: "${USERID}:${GROUPID}"
    ports:
      - "8080:8080"
  
  nginx:
    restart: unless-stopped
    container_name: nginx
    build:
      context: "./nginx"
      args: 
        NGINX_CONF: ${NGINX_CONF}
    volumes:
      - django:/www/site
      - static:/www/static
      - media:/www/media
      - log:/log
    ports: 
      - "80:80"
    depends_on: 
      - django
      - postgres
      - node
