version: '3.7'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/data/postgresdata
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/djangoVue/django
