version: '3.7'

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/postgresdata
  postgres_backup_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/postgresdata_backup_server
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/vue
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/log
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/static
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/media

services: 
  postgres:
    volumes:
      - postgres_backup_server:/var/backup_server

networks:
  default:
    external:
      name: nginx-proxy_default