version: '3.7'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/vue

services: 
  vue:
    build: 
      context: ./vue
    container_name: vue
    volumes:
      - ${PWD}/vue:/usr/src/app
    command: "npm run serve"
    user: "${USERID}:${GROUPID}"
    ports:
      - "8080:8080"
