version: '3.7'

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/data/postgresdata
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/vue
