version: '3.7'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/webserver/djangoVue/data/postgresdata
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/webserver/djangoVue/django
