version: '3.7'

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/data/postgresdata
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/django
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/vue
  nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/nginx
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/log
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/django/static
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${INSTALLFOLDER}/django/media

services:
  nginx:
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
  django:
    environment:
      VIRTUAL_PROTO: "uwsgi"

networks:
  default:
    external:
      name: nginx-proxy_default