version: '3.7'

services:  
  django:
    restart: always
    build: ./django
    container_name: django
    user: "${USER}:${GROUP}"
    environment:
      PYTHONUNBUFFERED: "TRUE"
    user: "${USERID}:${GROUPID}"
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    volumes:
      - django:/www/site
      - frontend:/www/site/frontend

  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}