version: '3'

services:  
  django:
    restart: always
    build: ./django
    container_name: django
    volumes:
      - ${PWD}/django:/www/site
      - ${PWD}/vue:/www/site/frontend
    environment:
      PYTHONUNBUFFERED: "TRUE"
    user: "${USERID}:${GROUPID}"
    ports:
      - "3000:3000"

  postgres:
    restart: always
    build: "./postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
