name: djangoVue
channels:
  - conda-forge
dependencies:
  - python
  - pylint
  - django
  - django-environ
  - djangorestframework
  - psycopg2
  - nodejs
  - yarn
  - gunicorn
  - whitenoise
  - pip:
    - django-webpack-loader
